name       : yubico-piv-tool
version    : 2.3.1
release    : 2
source     :
    - https://github.com/Yubico/yubico-piv-tool/archive/refs/tags/yubico-piv-tool-2.3.1.tar.gz : 11de1b708c6b917bec3da7d584f534a4314c51ccd461840fd16f15478ac2668f
license    : BSD-2-Clause
component  : security
summary    : Command line tool for the YubiKey PIV application
description: |
    The Yubico PIV tool is used for interacting with the Personal Identity Verification (PIV) application on a YubiKey. With it you may generate keys on the device, importing keys and certificates, and create certificate requests, and other operations. A shared library and a command-line tool is included.
builddeps  :
    - pkgconfig(check)
    - pkgconfig(libpcsclite)
    - gengetopt
    - help2man
setup      : |
    %cmake_ninja -DBUILD_STATIC_LIB=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Ensure p11tool from libgnutls-utils understands libykcs11 OOTB.
    install -Dm00644 $pkgfiles/ykcs11.module $installdir/etc/pkcs11/modules/yubico-piv.module
check      : |
    %ninja_check
